version: "3.9"

services:
  app:
    image: cosmtrek/air:v1.28.0
    working_dir: /app
    ports:
      - 3005:3005
    environment:
      - API_PORT=3005

  db:
    image: postgres:14.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=go-money-transfer
      - POSTGRES_PASSWORD=go-money-transfer
    volumes:
      - ./db/seed.sql:/docker-entrypoint-initdb.d/init.sql

  unittest:
    image: golang:1.19.0-alpine3.16
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      CGO_ENABLED: 0
      command: go test -v ./...